import type { Metadata } from "next";
import {
    Geist,
    Geist_Mono,
    Merienda,
    Roboto_Condensed,
    Rubik,
} from "next/font/google";
import "./globals.css";
import ClientProvider from "@/src/redux/ClientProvider";
import NavBar from "@/src/compnents/NavBar/NavBar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});
const merienda = Merienda({
    // variable: "--font-geist-sans",
    weight: "400",
    subsets: ["latin"],
});
const roboto = Roboto_Condensed({
    // variable: "--font-geist-sans",
    weight: "400",
    subsets: ["latin"],
});
const rubik = Rubik({
    // variable: "--font-geist-sans",
    weight: "400",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased transition-all`}
                style={{ fontFamily: "var(--font-rubik)" }}
            >
                <ClientProvider>
                    <NavBar />
                    {children}
                </ClientProvider>
            </body>
        </html>
    );
}
